Day 14 - API Calls/apiCalls/apiCalls/Models/ErrorViewModel.cs
namespace apiCalls.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Day 14 - API Calls/apiCalls/apiCalls/Controllers/ExternalDataController.cs
using Microsoft.AspNetCore.Mvc;

namespace apiCalls.Controllers
{
    public class ExternalDataController : Controller
    {
        public IActionResult PostData()
        {
            return View();
        }

        public IActionResult UserDetails()
        {
            return View();
        }
    }
}

Day 14 - API Calls/apiCalls/apiCalls/Controllers/HomeController.cs
using apiCalls.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace apiCalls.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Day 14 - API Calls/apiCalls/apiCalls/Views/ExternalData/PostData.cshtml
<script>
    function getPostData()
    {
        var dataUrl = "https://jsonplaceholder.typicode.com/posts";


        //fetch api is used to make api/rest calls, it is a standard built into every browser
        //fetch api,returns a promise, meaning, it is promising you that it will either get you the data or comeback with error
        fetch(dataUrl).then(dataFormat => dataFormat.json())
                      .then (data =>
                       { 
                         //   alert('Got the data, Success '); 
                          //  console.log(data);

                            //jquery to display the data

                            for(var i=0;i<data.length;i++)
                            {
                                    $("table").append("<tr>" + 
                                        "<td>" + data[i].id + "</td>" +
                                        "<td>" + data[i].userId + "</td>" +
                                        "<td>" + data[i].body + "</td>" +
                                        "<td>" + data[i].title + "</td>" +
                        "</tr>")
                            }
                            //we will write code to display the data, let us first test it
                       })
                        .catch( err =>
                         {
                            alert('Got Error');
                         })                   

    }
</script>



<button class="btn btn-danger" onclick="getPostData()">Show Post </button>

<table class="table table-bordered"></table>

Day 14 - API Calls/apiCalls/apiCalls/Views/ExternalData/UserDetails.cshtml
<script>


    function getUserDetails()
    {
        var userDataUrl = "https://jsonplaceholder.typicode.com/users";

        fetch(userDataUrl).then(format => format.json())
                          .then(userData => {
                              console.log(userData);

                              for(var i=0;i<userData.length;i++)
                              {
                                  $("table").append("<tr>" +
                                    "<td>" + userData[i].id + "</td>" + 
                                    "<td>" + userData[i].name + "</td>" + 
                                    "<td>" + userData[i].username + "</td>" + 
                                    "<td>" + userData[i].email + "</td>" +
                        "<td>" + userData[i].address.city + "</td>" +
                        "<td>" + userData[i].address.geo.lat + "</td>" +
                        "<td>" + userData[i].company.name + "</td>" +
                        "<td>" + userData[i].company.catchPhrase + "</td>" +

                                  
                                  + "</tr>")
                              }
                          })
                          .catch(errDetails =>{
                              console.log(errDetails);
                          })
    }
</script>


<table class="table table-stripped"></table>
<button class="btn btn-warning" onclick="getUserDetails()"> Display Users</button>

Day 14 - API Calls/apiCalls/apiCalls/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Day 14 - API Calls/apiCalls/apiCalls/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - apiCalls</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/apiCalls.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">apiCalls</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExternalData" asp-action="PostData">Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExternalData" asp-action="UserDetails">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - apiCalls - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>