Day 11 - MVC/shoppingAPP_mvc/shoppingAPP_mvc/Models/ErrorViewModel.cs
namespace shoppingAPP_mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Day 11 - MVC/shoppingAPP_mvc/shoppingAPP_mvc/Models/Products.cs
namespace shoppingAPP_mvc.Models
{
    public class Products
    {
        public int pId { get; set; }
        public string pName { get; set; }
        public string pCategory { get; set; }
        public int pPrice { get; set; }
        public bool pIsInStock { get; set; }

        static List<Products> pList = new List<Products>()
        {
            new Products(){ pId=101, pCategory="Cold-Drink", pName="Pepsi", pIsInStock=true, pPrice=50 },
            new Products(){ pId=102, pCategory="Electronics", pName="IPhone", pIsInStock=true, pPrice=50 },
            new Products(){ pId=103, pCategory="Electronics", pName="Air-Pods", pIsInStock=false, pPrice=50 },
            new Products(){ pId=104, pCategory="Shoe", pName="Nike", pIsInStock=true, pPrice=50 },
            new Products(){ pId=105, pCategory="Fast-Food", pName="Maggie", pIsInStock=true, pPrice=50 },
            new Products(){ pId=106, pCategory="Fast-Food", pName="Sandwitch", pIsInStock=false, pPrice=50 },
            new Products(){ pId=107, pCategory="Coffee", pName="Latte", pIsInStock=true, pPrice=50 },
        };

        public List<Products> GetAllProducts()
        {
            return pList;
        }
    }
}

Day 11 - MVC/shoppingAPP_mvc/shoppingAPP_mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using shoppingAPP_mvc.Models;
using System.Diagnostics;

namespace shoppingAPP_mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Day 11 - MVC/shoppingAPP_mvc/shoppingAPP_mvc/Controllers/productsController.cs
using Microsoft.AspNetCore.Mvc;
using shoppingAPP_mvc.Models;
namespace shoppingAPP_mvc.Controllers
{
    public class productsController : Controller
    {
     
        public IActionResult aboutAPP()
        {
            //collect data from Model, save it in ViewBag and it will be passed to view file
            ViewBag.appName = "Shopping APP";
            ViewBag.appDeveloper = "Nikhil Shah";
            ViewBag.appTeamSize = 20;
            ViewBag.appIsLive = false;
            return View();
        }

        public IActionResult ProductCategory()
        {
            //collect data from Model 
            List<string> categoryList = new List<string>() { "TShirts", "Shoes", "Head-Phones", "Speakers", "Tie", "Makeup" };
            ViewBag.productCategory = categoryList;
            return View();
        }

        public IActionResult ProductList()
        {
            Products pObj = new Products();
            ViewBag.pList = pObj.GetAllProducts();
            return View();
        }
    }
}

Day 11 - MVC/shoppingAPP_mvc/shoppingAPP_mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - shoppingAPP_mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/shoppingAPP_mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">shoppingAPP_mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>


                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="products" asp-action="aboutAPP">App Info</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="products" asp-action="ProductCategory">Categories</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="products" asp-action="ProductList">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - shoppingAPP_mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Day 11 - MVC/shoppingAPP_mvc/shoppingAPP_mvc/Views/products/ProductCategory.cshtml
<ul>
    @foreach (var item in ViewBag.productCategory)
    {
        <li> @item </li>
    }
</ul>

<select>
    @foreach (var item in ViewBag.productCategory)
    {
        <option> @item </option>
    }
</select>

<span>
    @foreach (var item in ViewBag.productCategory)
    {
        <input type="checkbox"/>@item
    }
</span>

Day 11 - MVC/shoppingAPP_mvc/shoppingAPP_mvc/Views/products/ProductList.cshtml
<h1> Hot Selling Products </h1>

<table class="table table-bordered">
    @foreach (var item in ViewBag.pList)
    {
        <tr>
            <td> @item.pId </td>
            <td> @item.pName </td>
            <td> @item.pCategory </td>
            <td> @item.pPrice </td>
            <td> @item.pIsInStock </td>
            <td> <input type="number" class="form-control" placeholder="enter qty" /> </td>
            <td> <button class="btn btn-primary">Add</button> </td>
        </tr>
    }
</table>

Day 11 - MVC/shoppingAPP_mvc/shoppingAPP_mvc/Views/products/aboutAPP.cshtml
<h1> About App Page </h1>


<div style="background-color:aqua">
<h2>  Name : @ViewBag.appName</h2>
<h2>  Developer : @ViewBag.appDeveloper</h2>
<h2>  Team Size : @ViewBag.appTeamSize</h2>
<h2>  Is Live : @ViewBag.appIsLive</h2>
</div>